"""Generic command package generation boundary."""

from __future__ import annotations

from command_generation.artifacts import CanonicalCommandArtifact, canonical_command_artifacts
from command_generation.conformance import (
    CliConformanceFailure,
    CliConformanceResult,
    CliConformanceTarget,
    FunctionConformanceFailure,
    FunctionConformanceResult,
    FunctionConformanceTarget,
    OperationConformanceCase,
    ProcessConformanceCase,
    TypescriptFunctionConformanceTarget,
    contract_conformance_cases_manifest,
    conformance_ownership_inventory,
    expected_contract_fields,
    invoke_typescript_operation,
    load_contract_conformance_case,
    materialize_case_fixture,
    operation_case_from_contract,
    process_case_from_contract,
    run_function_conformance_case,
    run_typescript_function_conformance_case,
    run_cli_conformance_case,
    selected_contract_fields,
    selected_result_fields,
    typescript_function_target,
)
from command_generation.generator import GeneratedOutput, generate_command_packages, generated_output_freshness_report, render_outputs
from command_generation.host_manifest import CommandGenerationHostManifest
from command_generation.ir import command_package_schema_path, load_command_package_ir
from command_generation.primitive_registry import BUILTIN_PORTABLE_PRIMITIVES, PrimitiveDefinition, PrimitiveRegistry
from command_generation.primitive_executor import PrimitiveContext, PrimitiveExecutionError, execute_primitive, run_operation_steps
from command_generation.target_extension import (
    TargetExtensionContract,
    TargetExtensionContractError,
    missing_target_proof_matrix_entries,
    required_target_proof_matrix_entries,
    target_extension_schema_path,
    target_support_matrix_entries,
    validate_target_extension_contract,
)

__all__ = [
    "BUILTIN_PORTABLE_PRIMITIVES",
    "CanonicalCommandArtifact",
    "CliConformanceFailure",
    "CliConformanceResult",
    "CliConformanceTarget",
    "CommandGenerationHostManifest",
    "FunctionConformanceFailure",
    "FunctionConformanceResult",
    "FunctionConformanceTarget",
    "GeneratedOutput",
    "OperationConformanceCase",
    "PrimitiveDefinition",
    "PrimitiveContext",
    "PrimitiveExecutionError",
    "ProcessConformanceCase",
    "PrimitiveRegistry",
    "TargetExtensionContract",
    "TargetExtensionContractError",
    "TypescriptFunctionConformanceTarget",
    "canonical_command_artifacts",
    "command_package_schema_path",
    "contract_conformance_cases_manifest",
    "conformance_ownership_inventory",
    "execute_primitive",
    "expected_contract_fields",
    "generate_command_packages",
    "generated_output_freshness_report",
    "invoke_typescript_operation",
    "load_command_package_ir",
    "load_contract_conformance_case",
    "materialize_case_fixture",
    "missing_target_proof_matrix_entries",
    "operation_case_from_contract",
    "process_case_from_contract",
    "required_target_proof_matrix_entries",
    "render_outputs",
    "run_function_conformance_case",
    "run_typescript_function_conformance_case",
    "run_cli_conformance_case",
    "run_operation_steps",
    "selected_contract_fields",
    "selected_result_fields",
    "target_extension_schema_path",
    "target_support_matrix_entries",
    "typescript_function_target",
    "validate_target_extension_contract",
]
