"""Generic command package generation boundary."""

from __future__ import annotations

from command_generation.artifacts import CanonicalCommandArtifact, canonical_command_artifacts
from command_generation.conformance import (
    CliConformanceFailure,
    CliConformanceResult,
    CliConformanceTarget,
    FunctionConformanceFailure,
    FunctionConformanceResult,
    FunctionConformanceTarget,
    OperationConformanceCase,
    ProcessConformanceCase,
    contract_conformance_cases_manifest,
    conformance_ownership_inventory,
    load_contract_conformance_case,
    materialize_case_fixture,
    operation_case_from_contract,
    process_case_from_contract,
    run_function_conformance_case,
    run_cli_conformance_case,
)
from command_generation.generator import GeneratedOutput, generate_command_packages, generated_output_freshness_report, render_outputs
from command_generation.host_manifest import CommandGenerationHostManifest
from command_generation.ir import command_package_schema_path, load_command_package_ir
from command_generation.primitive_registry import BUILTIN_PORTABLE_PRIMITIVES, PrimitiveDefinition, PrimitiveRegistry
from command_generation.target_extension import (
    TargetExtensionContract,
    TargetExtensionContractError,
    missing_target_proof_matrix_entries,
    required_target_proof_matrix_entries,
    target_extension_schema_path,
    target_support_matrix_entries,
    validate_target_extension_contract,
)

PUBLIC_API_CLASSIFICATION = {
    "BUILTIN_PORTABLE_PRIMITIVES": "stable",
    "CanonicalCommandArtifact": "stable",
    "CliConformanceFailure": "stable",
    "CliConformanceResult": "stable",
    "CliConformanceTarget": "stable",
    "CommandGenerationHostManifest": "stable",
    "FunctionConformanceFailure": "stable",
    "FunctionConformanceResult": "stable",
    "FunctionConformanceTarget": "stable",
    "GeneratedOutput": "stable",
    "OperationConformanceCase": "stable",
    "PrimitiveDefinition": "stable",
    "PrimitiveRegistry": "stable",
    "ProcessConformanceCase": "stable",
    "PUBLIC_API_CLASSIFICATION": "stable",
    "TargetExtensionContract": "stable",
    "TargetExtensionContractError": "stable",
    "canonical_command_artifacts": "stable",
    "command_package_schema_path": "stable",
    "contract_conformance_cases_manifest": "stable",
    "conformance_ownership_inventory": "stable",
    "generate_command_packages": "stable",
    "generated_output_freshness_report": "stable",
    "load_command_package_ir": "stable",
    "load_contract_conformance_case": "stable",
    "materialize_case_fixture": "stable",
    "missing_target_proof_matrix_entries": "stable",
    "operation_case_from_contract": "stable",
    "process_case_from_contract": "stable",
    "render_outputs": "stable",
    "required_target_proof_matrix_entries": "stable",
    "run_cli_conformance_case": "stable",
    "run_function_conformance_case": "stable",
    "target_extension_schema_path": "stable",
    "target_support_matrix_entries": "stable",
    "validate_target_extension_contract": "stable",
}

__all__ = [
    "BUILTIN_PORTABLE_PRIMITIVES",
    "CanonicalCommandArtifact",
    "CliConformanceFailure",
    "CliConformanceResult",
    "CliConformanceTarget",
    "CommandGenerationHostManifest",
    "FunctionConformanceFailure",
    "FunctionConformanceResult",
    "FunctionConformanceTarget",
    "GeneratedOutput",
    "OperationConformanceCase",
    "PrimitiveDefinition",
    "ProcessConformanceCase",
    "PrimitiveRegistry",
    "PUBLIC_API_CLASSIFICATION",
    "TargetExtensionContract",
    "TargetExtensionContractError",
    "canonical_command_artifacts",
    "command_package_schema_path",
    "contract_conformance_cases_manifest",
    "conformance_ownership_inventory",
    "generate_command_packages",
    "generated_output_freshness_report",
    "load_command_package_ir",
    "load_contract_conformance_case",
    "materialize_case_fixture",
    "missing_target_proof_matrix_entries",
    "operation_case_from_contract",
    "process_case_from_contract",
    "required_target_proof_matrix_entries",
    "render_outputs",
    "run_function_conformance_case",
    "run_cli_conformance_case",
    "target_extension_schema_path",
    "target_support_matrix_entries",
    "validate_target_extension_contract",
]
